### ISSUE TITLE
Upgrade to Tailwind v1

### ISSUE THREAD

**Issue by taylorbryant** [Oddstronaut/tailwind-jekyll#35]

**Comment by jacobpatton** [comment]
@taylorbryant thanks for all the work on this template app!

**Absolutely no pressure** -- do you have an idea when you might complete the upgrade to Tailwind v1?

I understand that Tailwind v1 was _just_ released, and I don't mean to hurry or hassle you. I'm in the midst of deciding on a CMS, and I'd prefer to use this Tailwind + Jekyll setup but lack the JS knowhow to complete the upgrade, myself (else I'd just do the work and submit a PR :-)

Thanks again!

**Comment by taylorbryant** [comment]
@jacobpatton I actually just updated it, so you should be good to go. 👍
